// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inherit;

namespace inherit.Migrations
{
    [DbContext(typeof(InheritDbContext))]
    partial class InheritDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("inherit.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasDiscriminator<string>("Name").HasValue("Vehicle");
                });

            modelBuilder.Entity("inherit.Airplane", b =>
                {
                    b.HasBaseType("inherit.Vehicle");

                    b.Property<string>("CruiseAltitude")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Airplane");
                });

            modelBuilder.Entity("inherit.Car", b =>
                {
                    b.HasBaseType("inherit.Vehicle");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("inherit.Vessel", b =>
                {
                    b.HasBaseType("inherit.Vehicle");

                    b.Property<string>("Bunker")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Vessel");
                });
#pragma warning restore 612, 618
        }
    }
}
